### ISSUE TITLE
Model not align？

### ISSUE THREAD

**Issue by tianhaowuhz** [geopavlakos/hamer#11]
Hi， I follow the installation to setup the environment. However, when I run the demo, it has following error.
<img width="766" alt="image" src="https://github.com/geopavlakos/hamer/assets/43113029/ac2dfc02-8dda-47ea-8e1e-7068cca288ad">

<img width="421" alt="image" src="https://github.com/geopavlakos/hamer/assets/43113029/4d2a56d1-403c-4bcf-b28b-3ffb48191cc6">

**Comment by geopavlakos** [comment]
The warnings of the first screenshot are expected so you shouldn't worry about it.
The error in the second screenshot seems to be due to detectron. Can you confirm that there is no error in the detectron installation (for example repeat the environment installation and look for any failures/errors)?

**Comment by tianhaowuhz** [comment]
Thank you for your suggestion! I finally found it is because the cuda version in my computer is not align, the detection is installed correctly
