### ISSUE TITLE
Running on small memory GPU?

### ISSUE THREAD

**Issue by tianhaowuhz** [geopavlakos/hamer#13]
Hi, I am trying to setup this algorithm in a 4060 GPU computer. However, it only has 8GB memory, which can not run this algorithm, I am wondering is there any arguments or something I can change to use less GPU memory, currently the batch size is only set to 1.
Thank you!

**Comment by geopavlakos** [comment]
Regarding the required memory, we updated the option for body detection in the demo (`body_detector` argument). Using the option `regnety` should run with less than 7GB of GPU memory and decrease runtime too. You might observe some small drop in accuracy when it comes to the hand detection aspect.

Regarding runtime in general, the demo can be slow, because it includes the body/hand detection, the rendering, and it also uses the tools with the highest accuracy for detection. You might want to simplify these aspects depending on the application (e.g., if you know the hand location, you can use that directly, or if you have a video, you might want to rely on tracking the hand instead of redetecting it in every frame).

**Comment by tianhaowuhz** [comment]
Thank you, I will try your suggestion
