### ISSUE TITLE
Input images of varying resolutions

### ISSUE THREAD

**Issue by richardrl** [geopavlakos/hamer#67]
In my experiments, Hamer seems to have decent performance on images of varying resolutions.

Did you find that performance was best at a certain resolution?

And is there any intuition for why it seems to work at different resolutions?  It seems in the original VIT paper they mentioned they needed to manually adjust the input for varying resolutions: https://arxiv.org/pdf/2010.11929, Section 3.2

Is it just because there is such a diversity of resolutions in the training data? I understand that the pipeline goes like this: VitDet bounding box -> VitPose keypoints -> bounding box from those keypoints -> resize crop to 256 x 256 -> go into Hamer.

**Comment by geopavlakos** [comment]
The key step here is that before processing the image with HaMeR, we always resize the hand crop to 256x256. This means that we are not really affected by the original resolution of the hand, since our network always processes images of a specific resolution.
With that being said, if the original resolution of the hand crop is much smaller than 256x256, then even if we upsample, the details of the hand won't be fully visible, so we expect a slightly lower quality in the reconstruction.
