### ISSUE TITLE
How to modify the focal length in the righy way

### ISSUE THREAD

**Issue by 1524101973** [geopavlakos/hamer#82]
Thank you for answer!
I have a question that rendering results differ with different focal length.
I only change the parameter here:
https://github.com/geopavlakos/hamer/blob/a489559381794934ce025f1122f461d0a9b08239/demo.py#L143
May I ask you is there any solution for this problem?

![0001_all3](https://github.com/user-attachments/assets/cd3525fc-4ed9-4e9c-89c3-6af4c1b7c2ff)
![0001_all1](https://github.com/user-attachments/assets/92ecf491-bd10-4510-b8f9-c6a82a929533)
![0001_all2](https://github.com/user-attachments/assets/a547bf49-cab4-4f25-a23f-243bb483ba63)

by the way I also tried with changing FOCAL_LENGTH in model_config.yaml according to the reply in
https://github.com/geopavlakos/hamer/issues/19#issue-2089645050

**Comment by 1524101973** [comment]
by the way I also tried with changing FOCAL_LENGTH in model_config.yaml according to the reply in
https://github.com/geopavlakos/hamer/issues/19#issue-2089645050

**Comment by geopavlakos** [comment]
The network does not consider the focal length value, so the hand pose and shape output will be the same even if you change this value. When a different focal length is used, the code is doing an approximation, so that the 3D location of the hand is roughly correct under the different intrinsics, but the rendering result will not be perfect.
